function [Xpos, Ypos, Angle] = importfile(filename, startRow, endRow)
    %IMPORTFILE Import numeric data from a text file as column vectors.
    %   [XPOS,YPOS,ANGLE] = IMPORTFILE(FILENAME) Reads data from text file
    %   FILENAME for the default selection.
    %
    %   [XPOS,YPOS,ANGLE] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
    %   from rows STARTROW through ENDROW of text file FILENAME.
    %
    % Example:
    %   [Xpos,Ypos,Angle] = importfile('Points.dat',1, 370);
    %
    %    See also TEXTSCAN.

    % Auto-generated by MATLAB on 2017/06/30 12:02:40

    %% Initialize variables.
    delimiter = ' ';

    if nargin <= 2
        startRow = 1;
        endRow = inf;
    end

    %% Format for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%f%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename, 'r');

    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1) - startRow(1) + 1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1) - 1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

    for block = 2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block) - startRow(block) + 1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block) - 1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

        for col = 1:length(dataArray)
            dataArray{col} = [dataArray{col}; dataArrayBlock{col}];
        end

    end

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Allocate imported array to column variable names
    Xpos = dataArray{:, 1};
    Ypos = dataArray{:, 2};
    Angle = dataArray{:, 3};
